### ISSUE TITLE
Python app blows up on contour map

### ISSUE THREAD

**Issue by bkbonner** [danpanaite/flutter_density_chart#1]
I tried running this on python3 and it blows up on the contour map:

2019-10-22 20:26:26.258 Python[15405:149677] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff3731d7f0 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit

[snip/]

127.0.0.1 - - [22/Oct/2019 20:26:26] "GET /shots/kde/contour?team=VGK&divisions=50 HTTP/1.1" 200 -
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894/AppKit.subproj/NSView.m, line 13528.
Illegal instruction: 4

I was intrigued by the post and trying to run the app with the web version of flutter.

It seemed to run ok, but the app server failed when it hit the kde/contour request

Have you seen this?   or were you running with Python 2?

**Comment by danpanaite** [comment]
Thanks for giving the code a try!

Are you trying to save or show the charts within the contour endpoint? It's a [common issue](https://stackoverflow.com/questions/53684971/assertion-failed-flask-server-stops-after-script-is-run) when running Matplotlib in a Flask server, where memory leaks can happen when the GUI windows fail to close properly. You can set Matplotlib to non-interactive by including `matplotlib.use('agg')` in the application.

If that doesn't work, you may want to check the version of your Matplotlib

**Comment by bkbonner** [comment]
Thanks for the quick response.  I'll give that a try.

**Comment by danpanaite** [comment]
I'll close this ticket for now, but let me know if you get into any other issues

**Comment by bkbonner** [comment]
Hi Dan,

I wasn't able to get it working with the ('agg').   I haven't tried it with
python 2.x yet.   As I said, I was more curious about how it worked in
Flutter Web, the datasets and how you handled the contour plots.
python(flask) isn't my specialty, so I'm not sure if I'm doing something
wrong.   Were you running it on python 3.x?  or 2.x?

This work was on a different computer that I don't have immediate access to.

Brian
